name: update

on:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: "master"
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - run: |
        echo ${{ secrets.GITHUB_TOKEN }} >> access_token.txt
        go run list2md.go
    - name: update the list
      env:
        GITHUB_USER: "mingrammer"
        GITHUB_EMAIL: "mingrammer@gmail.com"
      run: |
        git config user.name "${GITHUB_USER}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
        git commit -am "Auto update"
        git push -u origin master
